services:
  django_gunicorn:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static:/usr/src/app/static
      - ./:/usr/src/app
    command: gunicorn --reload --bind 0.0.0.0:8000 goprosperous.wsgi:application

  nginx:
    build: ./ngnix
    volumes:
      - static:/usr/src/app/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
volumes:
  static:
